using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using NexusStackNext.BuildingBlocks.Domain;
using NexusStackNext.BuildingBlocks.Infrastructure.Persistence;
using NexusStackNext.IntegrationSupport;
using Npgsql;

namespace NexusStackNext.BuildingBlocks.Infrastructure.IntegrationTests;

/// <summary>
/// EF Core 基座的约定，**在真实 PostgreSQL 上**验证。
///
/// <para><b>为什么不能在 InMemory provider 上验。</b>本票的阻塞点原文写着这一条：
/// "EF 的事务语义、<c>ValueGeneratedNever</c> 与数据库列的对应关系、
/// 软删过滤器翻译成的 SQL，都必须在真库上验证；用 InMemory provider 验证这些
/// 只会得到虚假的安全感（它没有事务，SQL 翻译也完全不同）。"</para>
///
/// <para>这里的每一条都对应票据 19 的一条验收。</para>
/// </summary>
public sealed class PersistenceConventionTests
{
    /// <summary>
    /// 迁移历史表必须落在**本上下文的 schema** 里。
    ///
    /// <para>这一条是实测出来的：<c>HasDefaultSchema</c> **不会**把
    /// <c>__EFMigrationsHistory</c> 一起 schema 化，它落在连接串的默认 schema（通常是 <c>public</c>）。
    /// 五个上下文因此会共用一张历史表，"每个上下文各自迁移"从结构上就不可能——
    /// 第二家跑迁移时会看到第一家已经建过的表。</para>
    /// </summary>
    [PostgresFact]
    public async Task MigrationsHistoryTable_IsQualifiedWithTheContextSchema()
    {
        await using var database = await PostgresTestDatabase.CreateAsync();
        await using var context = await ProbeDatabase.CreateAsync(database).ConfigureAwait(false);

        // 需求方是"表在哪个 schema 里"，所以比对**不带引号**的限定名：
        // EF 只在标识符需要转义时才加引号，而 `HasDefaultSchema` 产出的正是 `schema.table`。
        var extension = context.GetService<IDbContextOptions>()
            .Extensions
            .OfType<RelationalOptionsExtension>()
            .FirstOrDefault();

        Assert.NotNull(extension);
        Assert.Equal(NexusStackDbContextOptionsExtensions.MigrationsHistoryTableName, extension.MigrationsHistoryTableName);
        Assert.Equal(database.Schema, extension.MigrationsHistoryTableSchema);
    }

    /// <summary>建表 DDL 里，表名必须带上下文的 schema 前缀。</summary>
    [PostgresFact]
    public async Task GeneratedDdl_PlacesTablesInTheContextSchema()
    {
        await using var database = await PostgresTestDatabase.CreateAsync();
        await using var context = await ProbeDatabase.CreateAsync(database).ConfigureAwait(false);

        var ddl = context.Database.GenerateCreateScript();

        Assert.Contains($"{database.Schema}.probe_aggregate", ddl, StringComparison.Ordinal);

        // 顺带确认它**没有**落到 public ——这正是"漏配 schema"的症状，而且不会报错。
        Assert.DoesNotContain("public.probe_aggregate", ddl, StringComparison.Ordinal);
    }

    /// <summary>
    /// **主键由应用侧赋值，数据库列不带 IDENTITY**（ADR-0009）。
    ///
    /// <para>参照仓库在这里有两个权威并存：实体上标了 <c>ValueGeneratedNever</c>，
    /// 而迁移生成的列却带着自增——序列停在 1，与种子 admin 撞车。
    /// 所以这一条要查两处：**建表 DDL 里的列定义**，和**插入时数据库是否真的不生成标识**。</para>
    /// </summary>
    [PostgresFact]
    public async Task PrimaryKey_IsAssignedByTheApplication_NotTheDatabase()
    {
        await using var database = await PostgresTestDatabase.CreateAsync();
        await using var context = await ProbeDatabase.CreateAsync(database).ConfigureAwait(false);

        // 一、DDL 层面：列上不能有 IDENTITY。
        var ddl = context.Database.GenerateCreateScript();
        Assert.DoesNotContain("GENERATED BY DEFAULT AS IDENTITY", ddl, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("GENERATED ALWAYS AS IDENTITY", ddl, StringComparison.OrdinalIgnoreCase);

        // 二、目录层面：is_identity 必须是 NO（DDL 文本比对可能被格式变化骗过，这里查权威来源）。
        await using (var connection = await database.OpenAsync())
        {
            await using var command = new NpgsqlCommand(
                "select is_identity from information_schema.columns "
                + "where table_schema = @schema and table_name = 'probe_aggregate' and column_name = 'Id'",
                connection);

            command.Parameters.AddWithValue("schema", database.Schema);

            Assert.Equal("NO", (await command.ExecuteScalarAsync()) as string);
        }

        // 三、行为层面：一个**远离自增起点**的值，插进去原样读出来。
        const long assigned = 9_007_199_254_740_993L;

        context.Probes.Add(ProbeAggregate.Create(assigned, "由应用侧赋值"));
        await context.SaveChangesAsync();

        await using var verify = await database.OpenAsync();

        // **列名必须加引号。** EF 建出来的列是带引号的 `"Id"`（保留大小写），
        // 而 PostgreSQL 会把**不带引号**的标识符折叠成小写——`select Id` 于是变成 `id`，
        // 报 `42703: column "id" does not exist`。实测踩到过，症状离原因很远。
        await using var read = new NpgsqlCommand("select \"Id\" from probe_aggregate", verify);

        Assert.Equal(assigned, (long)(await read.ExecuteScalarAsync())!);
    }

    /// <summary>
    /// **软删记录不出现在常规查询里，但仍然在表中**（<see cref="ISoftDelete"/> 的契约）。
    ///
    /// <para>只测"查不到"是不够的：一条根本没写进去的记录同样查不到。
    /// 所以还要用**绕过 EF 过滤器**的原始 SQL 数一遍，证明它确实在表里。</para>
    /// </summary>
    [PostgresFact]
    public async Task SoftDeletedRow_IsHiddenFromQueries_ButStillInTheTable()
    {
        await using var database = await PostgresTestDatabase.CreateAsync();
        await using var context = await ProbeDatabase.CreateAsync(database).ConfigureAwait(false);

        context.Probes.Add(ProbeAggregate.Create(1, "保留"));
        context.Probes.Add(ProbeAggregate.Create(2, "软删"));
        await context.SaveChangesAsync();

        var doomed = await context.Probes.SingleAsync(probe => probe.Id == 2);
        doomed.SoftDelete();
        await context.SaveChangesAsync();

        // 常规查询看不到它。
        Assert.Equal(1, await context.Probes.CountAsync());

        // 但原始 SQL 数得到两行——它没有被物理删除。
        await using var connection = await database.OpenAsync();
        await using var count = new NpgsqlCommand("select count(*) from probe_aggregate", connection);

        Assert.Equal(2L, (long)(await count.ExecuteScalarAsync())!);
    }
}
