// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusStackNext.Platform.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusStackNext.Platform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261004141238_AuditedFactCapacityPolicy")]
    partial class AuditedFactCapacityPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RetryRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.HasIndex("EventName", "DeliveredAt", "Id")
                        .HasDatabaseName("ix_outbox_confirmed_event")
                        .HasFilter("\"DeliveredAt\" IS NOT NULL AND \"DeadLetteredAt\" IS NULL");

                    b.ToTable("outbox", "platform");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.CommittedFactCapacity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecordPayloadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("MaxRecords")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedRecords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("fact_capacity", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_fact_capacity_bounds", "\"RetainedRecords\" >= 0 AND \"RetainedPayloadBytes\" >= 0 AND \"MaxRecords\" > 0 AND \"MaxPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" <= \"MaxPayloadBytes\"");

                            t.HasCheckConstraint("ck_fact_capacity_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsumerName", "EventName", "MessageId");

                    b.ToTable("inbox", "platform");
                });

            modelBuilder.Entity("NexusStackNext.Platform.Domain.Settings.GlobalSetting", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("split_part(\"Key\", '.', 1)", true);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_global_settings_key");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_global_settings_scope");

                    b.ToTable("global_settings", "platform");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Events.FactPolicyControl", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecordPayloadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("MaxRecords")
                        .HasColumnType("bigint");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedRecords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("fact_policy_control", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_fact_policy_control_bounds", "\"PolicyRevision\" > 0 AND \"MaxRecords\" > 0 AND \"MaxPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" <= \"MaxPayloadBytes\" AND \"RetainedRecords\" >= 0 AND \"RetainedRecords\" <= \"MaxRecords\" AND \"RetainedPayloadBytes\" >= 0 AND \"RetainedPayloadBytes\" <= \"MaxPayloadBytes\"");

                            t.HasCheckConstraint("ck_fact_policy_control_singleton", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxPayloadBytes = 16777216L,
                            MaxRecordPayloadBytes = 16384,
                            MaxRecords = 1000L,
                            PolicyRevision = 1L,
                            RetainedPayloadBytes = 0L,
                            RetainedRecords = 0L
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Events.FactPolicyReceiptRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("PayloadBytes")
                        .HasColumnType("integer");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetainUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("RetainUntil", "RequestId");

                    b.ToTable("fact_policy_receipts", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_fact_policy_receipt_bytes", "\"PayloadBytes\" > 0");
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Events.FactPolicyReceiptRecord", b =>
                {
                    b.HasOne("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
