<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../NexusStackNext.Pricing.Domain/NexusStackNext.Pricing.Domain.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/BuildingBlocks.Application/BuildingBlocks.Application.csproj" />
    <ProjectReference Include="../../Files/NexusStackNext.Files.Contracts/NexusStackNext.Files.Contracts.csproj" />
  </ItemGroup>
</Project>
