<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Services/Scheduling/NexusStackNext.Scheduling.Contracts/NexusStackNext.Scheduling.Contracts.csproj" />
    <ProjectReference Include="../../src/Services/Pricing/NexusStackNext.Pricing.Infrastructure/NexusStackNext.Pricing.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Hosts/NexusStackNext.PricingHost/NexusStackNext.PricingHost.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../IntegrationSupport/IntegrationSupport.csproj" />
    <ProjectReference Include="../../src/Services/Costing/NexusStackNext.Costing.Infrastructure/NexusStackNext.Costing.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Hosts/NexusStackNext.CostingHost/NexusStackNext.CostingHost.csproj" />
    <ProjectReference Include="../../src/Gateway/NexusStackNext.Gateway/NexusStackNext.Gateway.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
