<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NexusStackNext.Auditing.Application</RootNamespace>
    <AssemblyName>NexusStackNext.Auditing.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../NexusStackNext.Auditing.Contracts/NexusStackNext.Auditing.Contracts.csproj" />
    <ProjectReference Include="../../Platform/NexusStackNext.Platform.Contracts/NexusStackNext.Platform.Contracts.csproj" />
    <ProjectReference Include="..\NexusStackNext.Auditing.Domain\NexusStackNext.Auditing.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
  </ItemGroup>

</Project>
