<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NexusStackNext.Scheduling.Application</RootNamespace>
    <AssemblyName>NexusStackNext.Scheduling.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../NexusStackNext.Scheduling.Contracts/NexusStackNext.Scheduling.Contracts.csproj" />
    <ProjectReference Include="../../Costing/NexusStackNext.Costing.Contracts/NexusStackNext.Costing.Contracts.csproj" />
    <ProjectReference Include="..\NexusStackNext.Scheduling.Domain\NexusStackNext.Scheduling.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
