<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../../Services/Pricing/NexusStackNext.Pricing.Endpoints/NexusStackNext.Pricing.Endpoints.csproj" />
    <ProjectReference Include="../../Composition/NexusStackNext.Composition/NexusStackNext.Composition.csproj" />
    <ProjectReference Include="../../../aspire/NexusStackNext.ServiceDefaults/NexusStackNext.ServiceDefaults.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>
</Project>
