<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NexusStackNext.Identity.Application</RootNamespace>
    <AssemblyName>NexusStackNext.Identity.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../NexusStackNext.Identity.Contracts/NexusStackNext.Identity.Contracts.csproj" />
    <ProjectReference Include="..\NexusStackNext.Identity.Domain\NexusStackNext.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
  </ItemGroup>

</Project>
