// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusStackNext.Auditing.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusStackNext.Auditing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditingDbContext))]
    [Migration("20261002171310_OperationObservations")]
    partial class OperationObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auditing")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusStackNext.Auditing.Domain.Entries.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt", "Id")
                        .HasDatabaseName("ix_audit_entries_recorded");

                    b.ToTable("audit_entries", "auditing");
                });

            modelBuilder.Entity("NexusStackNext.Auditing.Domain.Operations.OperationObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("operation_observations", "auditing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox", "auditing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsumerName", "EventName", "MessageId");

                    b.ToTable("inbox", "auditing");
                });

            modelBuilder.Entity("NexusStackNext.Auditing.Domain.Entries.AuditEntry", b =>
                {
                    b.OwnsOne("NexusStackNext.Auditing.Domain.Entries.AuditFact", "Fact", b1 =>
                        {
                            b1.Property<long>("AuditEntryId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Action");

                            b1.Property<string>("ActorId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ActorId");

                            b1.Property<string>("CorrelationId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("CorrelationId");

                            b1.Property<string>("EventName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("EventName");

                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid")
                                .HasColumnName("MessageId");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("OccurredAt");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Source");

                            b1.Property<string>("SubjectId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("SubjectId");

                            b1.Property<string>("SubjectType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("SubjectType");

                            b1.Property<long>("SubjectVersion")
                                .HasColumnType("bigint")
                                .HasColumnName("SubjectVersion");

                            b1.Property<string>("TraceId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("TraceId");

                            b1.HasKey("AuditEntryId");

                            b1.HasIndex("EventName", "MessageId")
                                .IsUnique();

                            b1.ToTable("audit_entries", "auditing");

                            b1.WithOwner()
                                .HasForeignKey("AuditEntryId");
                        });

                    b.Navigation("Fact")
                        .IsRequired();
                });

            modelBuilder.Entity("NexusStackNext.Auditing.Domain.Operations.OperationObservation", b =>
                {
                    b.OwnsOne("NexusStackNext.Auditing.Domain.Operations.OperationObservationData", "Data", b1 =>
                        {
                            b1.Property<Guid>("OperationObservationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ActorId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ActorId");

                            b1.Property<long?>("DurationMs")
                                .HasColumnType("bigint")
                                .HasColumnName("DurationMs");

                            b1.Property<string>("HttpMethod")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("HttpMethod");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("Kind");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("OccurredAt");

                            b1.Property<Guid>("OperationId")
                                .HasColumnType("uuid")
                                .HasColumnName("OperationId");

                            b1.Property<string>("Outcome")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("Outcome");

                            b1.Property<string>("Phase")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("Phase");

                            b1.Property<string>("RouteTemplate")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("RouteTemplate");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Source");

                            b1.Property<int?>("StatusCode")
                                .HasColumnType("integer")
                                .HasColumnName("StatusCode");

                            b1.Property<string>("TraceId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("TraceId");

                            b1.HasKey("OperationObservationId");

                            b1.HasIndex("OccurredAt", "Source", "OperationId")
                                .HasDatabaseName("ix_operation_observations_time");

                            b1.HasIndex("Source", "OperationId", "Phase")
                                .IsUnique()
                                .HasDatabaseName("ux_operation_observations_phase");

                            b1.ToTable("operation_observations", "auditing");

                            b1.WithOwner()
                                .HasForeignKey("OperationObservationId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
