// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusStackNext.Auditing.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusStackNext.Auditing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditingDbContext))]
    partial class AuditingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auditing")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusStackNext.Auditing.Domain.Entries.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt", "Id")
                        .HasDatabaseName("ix_audit_entries_recorded");

                    b.ToTable("audit_entries", "auditing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox", "auditing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsumerName", "EventName", "MessageId");

                    b.ToTable("inbox", "auditing");
                });

            modelBuilder.Entity("NexusStackNext.Auditing.Domain.Entries.AuditEntry", b =>
                {
                    b.OwnsOne("NexusStackNext.Auditing.Domain.Entries.AuditFact", "Fact", b1 =>
                        {
                            b1.Property<long>("AuditEntryId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Action");

                            b1.Property<string>("ActorId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ActorId");

                            b1.Property<string>("CorrelationId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("CorrelationId");

                            b1.Property<string>("EventName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("EventName");

                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid")
                                .HasColumnName("MessageId");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("OccurredAt");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Source");

                            b1.Property<string>("SubjectId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("SubjectId");

                            b1.Property<string>("SubjectType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("SubjectType");

                            b1.Property<long>("SubjectVersion")
                                .HasColumnType("bigint")
                                .HasColumnName("SubjectVersion");

                            b1.Property<string>("TraceId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("TraceId");

                            b1.HasKey("AuditEntryId");

                            b1.HasIndex("EventName", "MessageId")
                                .IsUnique();

                            b1.ToTable("audit_entries", "auditing");

                            b1.WithOwner()
                                .HasForeignKey("AuditEntryId");
                        });

                    b.Navigation("Fact")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
