<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NexusStackNext.BuildingBlocks.Web</RootNamespace>
    <AssemblyName>NexusStackNext.BuildingBlocks.Web</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../BuildingBlocks.Application/BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
