// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusStackNext.Pricing.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusStackNext.Pricing.Infrastructure.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20261009093209_PrivatePricingExports")]
    partial class PrivatePricingExports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RetryRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.HasIndex("EventName", "DeliveredAt", "Id")
                        .HasDatabaseName("ix_outbox_confirmed_event")
                        .HasFilter("\"DeliveredAt\" IS NOT NULL AND \"DeadLetteredAt\" IS NULL");

                    b.ToTable("outbox", "pricing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Events.FactPolicyControl", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecordPayloadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("MaxRecords")
                        .HasColumnType("bigint");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedRecords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("fact_policy_control", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_policy_control_bounds", "\"PolicyRevision\" > 0 AND \"MaxRecords\" > 0 AND \"MaxPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" <= \"MaxPayloadBytes\" AND \"RetainedRecords\" >= 0 AND \"RetainedRecords\" <= \"MaxRecords\" AND \"RetainedPayloadBytes\" >= 0 AND \"RetainedPayloadBytes\" <= \"MaxPayloadBytes\"");

                            t.HasCheckConstraint("ck_fact_policy_control_singleton", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxPayloadBytes = 16777216L,
                            MaxRecordPayloadBytes = 16384,
                            MaxRecords = 1000L,
                            PolicyRevision = 1L,
                            RetainedPayloadBytes = 0L,
                            RetainedRecords = 0L
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Events.FactPolicyReceiptRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("PayloadBytes")
                        .HasColumnType("integer");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetainUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("RetainUntil", "RequestId");

                    b.ToTable("fact_policy_receipts", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_policy_receipt_bytes", "\"PayloadBytes\" > 0");
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.CommittedFactCapacity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecordPayloadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("MaxRecords")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedRecords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("fact_capacity", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_capacity_bounds", "\"RetainedRecords\" >= 0 AND \"RetainedPayloadBytes\" >= 0 AND \"MaxRecords\" > 0 AND \"MaxPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" <= \"MaxPayloadBytes\"");

                            t.HasCheckConstraint("ck_fact_capacity_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("CostPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsumerName", "EventName", "MessageId");

                    b.ToTable("inbox", "pricing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Tasks.DurableTaskAttempt", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TaskId", "Epoch");

                    b.ToTable("attempts", "pricing");
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Domain.PriceQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BreakEvenPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("CalculatedRevision")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("CostingRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("FeeRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<long>("InputRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("quotes", "pricing");
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Domain.PricingExport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CanonicalRequest")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("character varying(262144)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExecutionOrigin")
                        .HasColumnType("jsonb");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("FileId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FrozenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MaxLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Producer")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PublicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublicationSelectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RequestDigestVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<long>("RetryRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("RowCount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("jsonb_array_length(\"Rows\")", true);

                    b.Property<string>("Rows")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SnapshotDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SnapshotDigestVersion")
                        .HasColumnType("integer");

                    b.Property<long>("SnapshotLength")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("UploadId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId")
                        .IsUnique()
                        .HasFilter("\"PublicationId\" IS NOT NULL");

                    b.HasIndex("OwnerId", "RequestId")
                        .IsUnique();

                    b.HasIndex("AvailableAt", "AcceptedAt", "Id")
                        .HasFilter("\"State\" = 'Queued'");

                    b.HasIndex("LeaseUntil", "AcceptedAt", "Id")
                        .HasFilter("\"State\" = 'Generating'");

                    b.HasIndex("OwnerId", "AcceptedAt", "Id");

                    b.ToTable("exports", "pricing");
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Infrastructure.PriceCacheInvalidation", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId", "Version");

                    b.ToTable("cache_invalidations", "pricing");
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Infrastructure.PricingAuditRecoveryControl", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecordPayloadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("MaxRecords")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedRecords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("fact_recovery_control", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_recovery_control_bounds", "\"MaxRecords\" > 0 AND \"MaxPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" <= \"MaxPayloadBytes\" AND \"RetainedRecords\" >= 0 AND \"RetainedRecords\" <= \"MaxRecords\" AND \"RetainedPayloadBytes\" >= 0 AND \"RetainedPayloadBytes\" <= \"MaxPayloadBytes\"");

                            t.HasCheckConstraint("ck_fact_recovery_control_singleton", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxPayloadBytes = 16777216L,
                            MaxRecordPayloadBytes = 16384,
                            MaxRecords = 1000L,
                            RetainedPayloadBytes = 0L,
                            RetainedRecords = 0L
                        });
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Infrastructure.PricingAuditRecoveryRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("PayloadBytes")
                        .HasColumnType("integer");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetainUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("RetainUntil", "RequestId");

                    b.ToTable("fact_recovery_receipts", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_recovery_receipt_bytes", "\"PayloadBytes\" > 0");
                        });
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Infrastructure.PricingExportPublication", b =>
                {
                    b.Property<Guid>("PublicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ExportId")
                        .HasColumnType("uuid");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MaxLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("RetryRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SelectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid");

                    b.HasKey("PublicationId");

                    b.HasIndex("ExportId")
                        .IsUnique();

                    b.HasIndex("State", "AvailableAt", "PublicationId");

                    b.ToTable("export_publications", "pricing");
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Infrastructure.RecalculationEntry", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("integer");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExecutionOrigin")
                        .HasColumnType("jsonb");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FeeRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<long>("InputRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MaxLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("manual");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("TaskId");

                    b.HasIndex("ItemId");

                    b.HasIndex("State", "AvailableAt");

                    b.ToTable("tasks", "pricing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Events.FactPolicyReceiptRecord", b =>
                {
                    b.HasOne("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Tasks.DurableTaskAttempt", b =>
                {
                    b.HasOne("NexusStackNext.Pricing.Infrastructure.RecalculationEntry", null)
                        .WithMany("History")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Infrastructure.PricingExportPublication", b =>
                {
                    b.HasOne("NexusStackNext.Pricing.Domain.PricingExport", null)
                        .WithOne()
                        .HasForeignKey("NexusStackNext.Pricing.Infrastructure.PricingExportPublication", "ExportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Infrastructure.RecalculationEntry", b =>
                {
                    b.HasOne("NexusStackNext.Pricing.Domain.PriceQuote", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusStackNext.Pricing.Infrastructure.RecalculationEntry", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
