#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — 本仓的三件"只有人能做"的事。
#
# 每个捕获的值：从哪来 / 写到哪 / 是不是秘密：
#
#   | 值                        | 从哪来                              | 写到                | 秘密 |
#   |---|---|---|---|
#   | AgileConfig 地址（Nodes） | 部署配置中心的那台机器               | platform.dev + gateway.dev | 否 |
#   | 平台应用 AppId            | 后台 · 应用列表                     | platform.dev        | 否 |
#   | 平台应用 Secret           | 后台 · 应用列表 · 眼睛图标           | platform.dev        | **是** |
#   | 网关应用 AppId / Secret   | 同上（另一个应用）                   | gateway.dev         | 否 / **是** |
#   | Jwt__SigningKey           | **本脚本生成**（两个宿主共用一把）    | platform.dev + gateway.dev | **是** |
#   | RabbitMQ 口令             | 部署 broker 的那台机器               | platform.dev        | **是** |
#   | 测试库 / broker 连接串     | 部署测试依赖的那台机器               | test.dev            | **是** |
#
# **没有 set_secret**：CI 里 `secrets.*` / `vars.*` 的引用数是 0（`.github/workflows/ci.yml`
# 实测），所以没有任何值需要进 GitHub secret。技能里那条"只设 CI 真正需要的"在这里就是"一个都不设"。
#
# 三个 env 文件都在 `.gitignore` 里（`env/*.dev`），这可能是它们最要紧的性质。
# ──────────────────────────────────────────────────────────────────────────

WIZARD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$WIZARD_DIR/.." && pwd)"

# 允许把写入位置挪走：冒烟测试用得上（否则它会把空值写进真正的 env 文件）。
ENV_DIR="${NEXUSSTACK_ENV_DIR:-$REPO_ROOT/env}"

PLATFORM_ENV="$ENV_DIR/platform.dev"
GATEWAY_ENV="$ENV_DIR/gateway.dev"
TEST_ENV="$ENV_DIR/test.dev"

mkdir -p "$ENV_DIR"

TOTAL_STAGES=5

banner "NexusStackNext 本机设置"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "配置中心 · 平台应用"
say "平台宿主启动时要连配置中心。先给它一个地址，再给它一个应用身份。"
note "如果你还没有配置中心：ADR-0012 规定的是 1 个基座应用 + 2 个宿主应用"
note "（nexusstack_shared → nexusstack_gateway / nexusstack_platform）。"
echo
ask AGILECONFIG_NODES "配置中心地址（例如 http://your-agileconfig:8010）："
ENV_FILE="$PLATFORM_ENV"   # 库从这里读/写；见文件头的表
open_url "$AGILECONFIG_NODES"
step "在后台左侧打开「应用列表」，找到平台宿主那个应用（默认 nexusstack_platform）。"
ask AgileConfig__AppId "平台应用的 AppId（应用列表里那一列，直接抄）："
step "同一行右侧的**眼睛图标**——点开就是 Secret，复制它。"
ask_secret AgileConfig__Secret "平台应用的 Secret（输入不回显）："
ask AgileConfig__Env "环境标识（DEV / TEST / PROD，回车用 DEV）："
[[ -z "${AgileConfig__Env:-}" ]] && AgileConfig__Env=DEV
write_env AgileConfig__Nodes "$AGILECONFIG_NODES"
write_env AgileConfig__AppId "$AgileConfig__AppId"
write_env AgileConfig__Secret "$AgileConfig__Secret"
write_env AgileConfig__Env "$AgileConfig__Env"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "配置中心 · 网关应用"
say "网关是**另一个**应用（它的配置与平台宿主不该混在一起）。"
note "地址用上一步填过的那个，不用再抄一遍。"
ENV_FILE="$GATEWAY_ENV"
step "回到「应用列表」，这次找网关那个应用（默认 nexusstack_gateway）。"
ask AgileConfig__AppId "网关应用的 AppId："
step "同样点眼睛图标复制 Secret。"
ask_secret AgileConfig__Secret "网关应用的 Secret（输入不回显）："
ask AgileConfig__Env "环境标识（DEV / TEST / PROD，回车用 DEV）："
[[ -z "${AgileConfig__Env:-}" ]] && AgileConfig__Env=DEV
write_env AgileConfig__Nodes "$AGILECONFIG_NODES"
write_env AgileConfig__AppId "$AgileConfig__AppId"
write_env AgileConfig__Secret "$AgileConfig__Secret"
write_env AgileConfig__Env "$AgileConfig__Env"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "JWT 签名密钥"
say "两个宿主共用同一把密钥：Identity 签发，网关验签。"
note "没有它，平台宿主**启动即失败**（OptionsValidationException，至少 32 字节）——这是有意的；"
note "网关那边不对称：缺它时照常启动，而所有要求认证的路由一律 401（fail-closed）。"
ENV_FILE="$PLATFORM_ENV"
if [[ -n "$(_existing Jwt__SigningKey || true)" ]]; then
  note "已有 Jwt__SigningKey，保留原值不动（要轮换就手动改这两个文件）。"
else
  step "这一项不用你抄——本脚本生成一个 48 字节的随机串，并且**不回显**。"
  if command -v openssl >/dev/null 2>&1; then
    Jwt__SigningKey="$(openssl rand -base64 48 | tr -d '\n')"
  else
    Jwt__SigningKey="$(head -c 48 /dev/urandom | base64 | tr -d '\n')"
  fi
  write_env Jwt__SigningKey "$Jwt__SigningKey"
  ENV_FILE="$GATEWAY_ENV"
  write_env Jwt__SigningKey "$Jwt__SigningKey"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "RabbitMQ（可选）"
say "不配它平台宿主也能跑：消息基座有内存实现，端到端旅程照样通。"
if confirm "配一个真实的 broker（集成测试与真投递需要它）？"; then
  ENV_FILE="$PLATFORM_ENV"
  ask RabbitMQ__HostName "broker 主机（回车用 localhost）："
  [[ -z "${RabbitMQ__HostName:-}" ]] && RabbitMQ__HostName=localhost
  ask RabbitMQ__Port "端口（回车用 5672）："
  [[ -z "${RabbitMQ__Port:-}" ]] && RabbitMQ__Port=5672
  ask RabbitMQ__UserName "用户名（回车用 guest）："
  [[ -z "${RabbitMQ__UserName:-}" ]] && RabbitMQ__UserName=guest
  ask_secret RabbitMQ__Password "口令（输入不回显）："
  ask RabbitMQ__VirtualHost "VirtualHost（回车用 /）："
  [[ -z "${RabbitMQ__VirtualHost:-}" ]] && RabbitMQ__VirtualHost=/
  ask RabbitMQ__ClientName "ClientName（回车用 nexusstack-platform-host）："
  [[ -z "${RabbitMQ__ClientName:-}" ]] && RabbitMQ__ClientName=nexusstack-platform-host
  write_env RabbitMQ__HostName "$RabbitMQ__HostName"
  write_env RabbitMQ__Port "$RabbitMQ__Port"
  write_env RabbitMQ__UserName "$RabbitMQ__UserName"
  write_env RabbitMQ__Password "$RabbitMQ__Password"
  write_env RabbitMQ__VirtualHost "$RabbitMQ__VirtualHost"
  write_env RabbitMQ__ClientName "$RabbitMQ__ClientName"
else
  note "跳过。之后要加，重跑本脚本（已有的值会作为默认值保留）。"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "集成测试的依赖（可选）"
say "仓库自带的集成测试连真 PostgreSQL 与真 broker；两条连接串放在 test.dev 里。"
warn "那台库**不只你在用**——AGENTS.md 记着一次事故：并行跑满测试把它压垮，"
warn "连带配置中心崩掉、机器卡死。所以全量测试一律走 scripts/run-tests.ps1（串行 + 互斥）。"
if confirm "现在填这两条连接串？"; then
  ENV_FILE="$TEST_ENV"
  ask_secret NEXUSSTACK_TEST_POSTGRES "PostgreSQL 连接串（输入不回显）："
  ask_secret NEXUSSTACK_TEST_RABBITMQ "RabbitMQ 连接串（输入不回显）："
  write_env NEXUSSTACK_TEST_POSTGRES "$NEXUSSTACK_TEST_POSTGRES"
  write_env NEXUSSTACK_TEST_RABBITMQ "$NEXUSSTACK_TEST_RABBITMQ"
else
  note "跳过。缺这两项时，集成测试会**跳过并说明原因**——而不是假装通过。"
fi

finish

# 收尾说三件脚本不该替你决定的事（`finish` 之后仍会显示）。
printf '%s下一步%s\n' "$BOLD" "$RESET"
printf '  %s• 起平台宿主：%s pwsh -File scripts/run-host.ps1 platform\n' "$BLUE" "$RESET"
printf '  %s• 起网关：    %s pwsh -File scripts/run-host.ps1 gateway\n' "$BLUE" "$RESET"
printf '  %s• 走一遍真实旅程：%s pwsh -File scripts/verify-user-journey.ps1\n' "$BLUE" "$RESET"
printf '  %s  三个 env 文件都在 .gitignore 里（env/*.dev）——别把它们提交上去。%s\n\n' "$DIM" "$RESET"
