namespace NexusStackNext.BuildingBlocks.Application.Ids;

/// <summary>
/// 应用侧主键生成器（ADR-0009）。
/// <para>
/// <b>ID 由应用侧生成，数据库不做 IDENTITY</b>——参照仓库两个权威并存
/// （构造函数赋雪花 ID + 22 张表全是 <c>GENERATED BY DEFAULT AS IDENTITY</c>），
/// 结果是序列停在 1，任何走数据库生成路径的插入都会拿到 <c>1</c>，与种子 admin 相撞。
/// </para>
/// <para>
/// 作为显式依赖注入，<b>不是静态单例</b>——参照仓库的 <c>SnowFlake.Instance</c> 正是让
/// <c>new User()</c> 在单元测试里抛异常的元凶（<c>AGENTS.md</c> 不变量 6）。
/// </para>
/// </summary>
public interface IIdGenerator
{
    /// <summary>生成一个全局唯一、随时间单调递增的 ID。</summary>
    /// <returns>新 ID。</returns>
    long NextId();
}
