<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../Auditing/NexusStackNext.Auditing.Contracts/NexusStackNext.Auditing.Contracts.csproj" />
    <ProjectReference Include="../NexusStackNext.Costing.Infrastructure/NexusStackNext.Costing.Infrastructure.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/BuildingBlocks.Web/BuildingBlocks.Web.csproj" />
  </ItemGroup>
</Project>
