<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../NexusStackNext.Pricing.Infrastructure/NexusStackNext.Pricing.Infrastructure.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/BuildingBlocks.Web/BuildingBlocks.Web.csproj" />
  </ItemGroup>
</Project>
