// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusStackNext.Auditing.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusStackNext.Auditing.Infrastructure.Persistence.OperationJournal.Migrations
{
    [DbContext(typeof(OperationJournalDbContext))]
    [Migration("20261003085126_JournalRecoveryRetention")]
    partial class JournalRecoveryRetention
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operation_journal")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusStackNext.Auditing.Infrastructure.Persistence.OperationJournalCapacity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("PayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RecordCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("capacity", "operation_journal", t =>
                        {
                            t.HasCheckConstraint("ck_capacity_valid", "\"Id\" = 1 AND \"RecordCount\" >= 0 AND \"PayloadBytes\" >= 0");
                        });
                });

            modelBuilder.Entity("NexusStackNext.Auditing.Infrastructure.Persistence.OperationJournalRecoveryRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<long>("PreviousRetryRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("RecoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RetainUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RetryRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("RetainUntil", "RequestId");

                    b.ToTable("recovery_records", "operation_journal", t =>
                        {
                            t.HasCheckConstraint("ck_recovery_revision", "\"PreviousRetryRevision\" >= 0 AND \"RetryRevision\" = \"PreviousRetryRevision\" + 1");
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("RetryRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAt", "Id")
                        .HasDatabaseName("ix_outbox_delivered_cleanup")
                        .HasFilter("\"DeliveredAt\" IS NOT NULL AND \"DeadLetteredAt\" IS NULL");

                    b.HasIndex("DeliveredAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.HasIndex("Source", "OperationId", "Phase")
                        .IsUnique();

                    b.ToTable("outbox", "operation_journal");
                });
#pragma warning restore 612, 618
        }
    }
}
