// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusStackNext.Costing.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusStackNext.Costing.Infrastructure.Migrations
{
    [DbContext(typeof(CostingDbContext))]
    [Migration("20261008130716_CostBatchInput")]
    partial class CostBatchInput
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("costing")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RetryRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.HasIndex("EventName", "DeliveredAt", "Id")
                        .HasDatabaseName("ix_outbox_confirmed_event")
                        .HasFilter("\"DeliveredAt\" IS NOT NULL AND \"DeadLetteredAt\" IS NULL");

                    b.ToTable("outbox", "costing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Events.FactPolicyControl", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecordPayloadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("MaxRecords")
                        .HasColumnType("bigint");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedRecords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("fact_policy_control", "costing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_policy_control_bounds", "\"PolicyRevision\" > 0 AND \"MaxRecords\" > 0 AND \"MaxPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" <= \"MaxPayloadBytes\" AND \"RetainedRecords\" >= 0 AND \"RetainedRecords\" <= \"MaxRecords\" AND \"RetainedPayloadBytes\" >= 0 AND \"RetainedPayloadBytes\" <= \"MaxPayloadBytes\"");

                            t.HasCheckConstraint("ck_fact_policy_control_singleton", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxPayloadBytes = 16777216L,
                            MaxRecordPayloadBytes = 16384,
                            MaxRecords = 1000L,
                            PolicyRevision = 1L,
                            RetainedPayloadBytes = 0L,
                            RetainedRecords = 0L
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Events.FactPolicyReceiptRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("PayloadBytes")
                        .HasColumnType("integer");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetainUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("RetainUntil", "RequestId");

                    b.ToTable("fact_policy_receipts", "costing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_policy_receipt_bytes", "\"PayloadBytes\" > 0");
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.CommittedFactCapacity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecordPayloadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("MaxRecords")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedRecords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("fact_capacity", "costing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_capacity_bounds", "\"RetainedRecords\" >= 0 AND \"RetainedPayloadBytes\" >= 0 AND \"MaxRecords\" > 0 AND \"MaxPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" <= \"MaxPayloadBytes\"");

                            t.HasCheckConstraint("ck_fact_capacity_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsumerName", "EventName", "MessageId");

                    b.ToTable("inbox", "costing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Tasks.DurableTaskAttempt", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TaskId", "Epoch");

                    b.ToTable("attempts", "costing");
                });

            modelBuilder.Entity("NexusStackNext.Costing.Domain.CostSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("CalculatedRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("FreightCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("InputRevision")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PurchaseCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("sheets", "costing");
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.CostBatchEntry", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Checkpoint")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuplicateSuperseded")
                        .HasColumnType("integer");

                    b.Property<int>("Imported")
                        .HasColumnType("integer");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<int>("Unchanged")
                        .HasColumnType("integer");

                    b.HasKey("BatchId");

                    b.HasIndex("CreatedAt", "BatchId");

                    b.ToTable("batches", "costing");
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.CostBatchRowEntry", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("EffectiveSequence")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FreightCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("PurchaseCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("SourceRow")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("BatchId", "Sequence");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("batch_rows", "costing");
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.CostCalculationEntry", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("integer");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExecutionOrigin")
                        .HasColumnType("jsonb");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FreightCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("InputRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MaxLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("manual");

                    b.Property<decimal>("PurchaseCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("TaskId");

                    b.HasIndex("ItemId");

                    b.HasIndex("State", "AvailableAt");

                    b.ToTable("tasks", "costing");
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.CostingAuditRecoveryControl", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecordPayloadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("MaxRecords")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedRecords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("fact_recovery_control", "costing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_recovery_control_bounds", "\"MaxRecords\" > 0 AND \"MaxPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" <= \"MaxPayloadBytes\" AND \"RetainedRecords\" >= 0 AND \"RetainedRecords\" <= \"MaxRecords\" AND \"RetainedPayloadBytes\" >= 0 AND \"RetainedPayloadBytes\" <= \"MaxPayloadBytes\"");

                            t.HasCheckConstraint("ck_fact_recovery_control_singleton", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxPayloadBytes = 16777216L,
                            MaxRecordPayloadBytes = 16384,
                            MaxRecords = 1000L,
                            RetainedPayloadBytes = 0L,
                            RetainedRecords = 0L
                        });
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.CostingAuditRecoveryRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("PayloadBytes")
                        .HasColumnType("integer");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetainUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("RetainUntil", "RequestId");

                    b.ToTable("fact_recovery_receipts", "costing", t =>
                        {
                            t.HasCheckConstraint("ck_fact_recovery_receipt_bytes", "\"PayloadBytes\" > 0");
                        });
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.ScheduledCostReceiptEntry", b =>
                {
                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<long>("TriggerSequence")
                        .HasColumnType("bigint");

                    b.HasKey("OccurrenceId");

                    b.HasIndex("TaskId");

                    b.ToTable("schedule_receipts", "costing");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Events.FactPolicyReceiptRecord", b =>
                {
                    b.HasOne("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Tasks.DurableTaskAttempt", b =>
                {
                    b.HasOne("NexusStackNext.Costing.Infrastructure.CostCalculationEntry", null)
                        .WithMany("History")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.CostBatchRowEntry", b =>
                {
                    b.HasOne("NexusStackNext.Costing.Infrastructure.CostBatchEntry", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.CostCalculationEntry", b =>
                {
                    b.HasOne("NexusStackNext.Costing.Domain.CostSheet", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.ScheduledCostReceiptEntry", b =>
                {
                    b.HasOne("NexusStackNext.Costing.Infrastructure.CostCalculationEntry", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NexusStackNext.Costing.Infrastructure.CostCalculationEntry", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
