// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusStackNext.Scheduling.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusStackNext.Scheduling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20261004065840_FactCapacityWaitBudget")]
    partial class FactCapacityWaitBudget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Application.Events.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RetryRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.HasIndex("EventName", "DeliveredAt", "Id")
                        .HasDatabaseName("ix_outbox_confirmed_event")
                        .HasFilter("\"DeliveredAt\" IS NOT NULL AND \"DeadLetteredAt\" IS NULL");

                    b.ToTable("outbox", "scheduling");
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.CommittedFactCapacity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecordPayloadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("MaxRecords")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedRecords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("fact_capacity", "scheduling", t =>
                        {
                            t.HasCheckConstraint("ck_fact_capacity_bounds", "\"RetainedRecords\" >= 0 AND \"RetainedPayloadBytes\" >= 0 AND \"MaxRecords\" > 0 AND \"MaxPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" > 0 AND \"MaxRecordPayloadBytes\" <= \"MaxPayloadBytes\"");

                            t.HasCheckConstraint("ck_fact_capacity_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("NexusStackNext.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsumerName", "EventName", "MessageId");

                    b.ToTable("inbox", "scheduling");
                });

            modelBuilder.Entity("NexusStackNext.Scheduling.Application.ScheduleDecision", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlanVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ScheduleRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DecisionId");

                    b.HasIndex("PlanId", "PlanVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_decisions_plan_version");

                    b.ToTable("decisions", "scheduling");
                });

            modelBuilder.Entity("NexusStackNext.Scheduling.Application.ScheduleOccurrence", b =>
                {
                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExecutionOrigin")
                        .HasColumnType("jsonb");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TriggerSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OccurrenceId");

                    b.HasIndex("PlanId", "TriggerSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_occurrences_plan_sequence");

                    b.ToTable("occurrences", "scheduling");
                });

            modelBuilder.Entity("NexusStackNext.Scheduling.Domain.Tasks.ScheduledTask", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DelegatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExecutionOrigin")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSchedulingErrorCode")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ScheduleRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("SchedulingFailureCount")
                        .HasColumnType("integer");

                    b.Property<long>("TriggerSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_plans_code");

                    b.HasIndex("IsEnabled", "NextRunAt", "Id")
                        .HasDatabaseName("ix_plans_due");

                    b.ToTable("plans", "scheduling");
                });

            modelBuilder.Entity("NexusStackNext.Scheduling.Domain.Tasks.ScheduledTask", b =>
                {
                    b.OwnsOne("NexusStackNext.Scheduling.Domain.Tasks.ScheduleRule", "Rule", b1 =>
                        {
                            b1.Property<long>("ScheduledTaskId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("CronFieldCount")
                                .HasColumnType("integer")
                                .HasColumnName("CronFieldCount");

                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("Day");

                            b1.Property<string>("Expression")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Expression");

                            b1.Property<double?>("GraceSeconds")
                                .HasColumnType("double precision")
                                .HasColumnName("GraceSeconds");

                            b1.Property<int?>("Hour")
                                .HasColumnType("integer")
                                .HasColumnName("Hour");

                            b1.Property<TimeSpan?>("IntervalSeconds")
                                .HasColumnType("interval")
                                .HasColumnName("Interval");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("RuleKind");

                            b1.Property<int?>("Minute")
                                .HasColumnType("integer")
                                .HasColumnName("Minute");

                            b1.Property<string>("MisfirePolicy")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("MisfirePolicy");

                            b1.Property<string>("TimeZoneId")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("TimeZoneId");

                            b1.HasKey("ScheduledTaskId");

                            b1.ToTable("plans", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("ScheduledTaskId");
                        });

                    b.OwnsOne("NexusStackNext.Scheduling.Domain.Tasks.ScheduleTarget", "Target", b1 =>
                        {
                            b1.Property<long>("ScheduledTaskId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("TargetKind");

                            b1.Property<Guid>("SubjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("TargetId");

                            b1.HasKey("ScheduledTaskId");

                            b1.ToTable("plans", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("ScheduledTaskId");
                        });

                    b.Navigation("Rule")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
